### PR TITLE
Adapt styles of the homepage sections

### PR DESCRIPTION
**Pull request by SantosGuillamot**
Still to do:
- [x] Position the header as absolute/fixed and make it transparent
- [x] ~Add back the background triangles and fix the transparency of the containing element~ (gonna make background an SVG
- [x] Add the `V` after the "why react?" & "why wordpress?" sections
- [x] ~Remove the "text-align: center" in gutenberg and align the descriptions and titles to the left. This one I think is not 100% necessary I would say because~
- [x] Add the numbers for the list in "Frontity is as fast as a static site gen..." (override `list-style-type: none`)
- [x] Fix the layout of the `Why Frontity?` section on tablet
- [x] Correct margins and padding on all sections below the `wrapping-section`
- [x] Add the V clip-path to the top of the footer 
- [x] Fix the padding of the header on tablet sizes
- [x] Icons of header get "squashed" on tablet sizes
- [ ] Try to fix the pixelated frontity logo (next to the iframe) when navigating the pages
- [ ] Make Hero background an SVG (to add the triangles)

After #77 is merged:
- [ ] Align the 'terminal' and image elements in the Hero alongside the title 

Mario: 
- [ ] Check if all links are correct (in header, footer, and for all buttons)
- [ ] Add all the correct assets in WP (images, etc)
- [ ] Add the icon above the "Designed for Performance" section
- [ ] Check if scrollbars are working correctly

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 0161ac62ec66d3a69874599e04fb441027f427bb

https://frontity-org-41bete2mx.now.sh

**Comment by michalczaplinski** [comment]
@SantosGuillamot I have made many small changes to fix the layout, margins and clip-paths on both mobile and desktop so check it out so that we don't duplicate any work.

1. I've just removed the triangles from the hero for now, because they were interfering with the background color of the hero. I think we can just remove them for good or find a better way to implement. Your call 🙂 

2. Jude is going to layout the terminal element in the hero correctly after adding the animation so for now it's still not correct.

Still do to (this is not a complete and full list I guess):
- [ ] Correct margins and padding on all sections below the `wrapping-section`
- [ ] Check if all links are correct (in header, footer, and for all buttons)
- [ ] Fix the padding of the header on tablet sizes
- [ ] Icons of header get "squashed" on tablet sizes
- [ ] Add all the correct assets in WP (images, etc)
- [ ] Remove the "text-align: center" in gutenberg and align the descriptions and titles to the left. This one I think is not 100% necessary I would say because 
- [ ] Add the numbers for the list in "Frontity is as fast as a static site gen..." (override `list-style-type: none`)

(i've copied the TODO list to the top of the PR as well)

**Comment by SantosGuillamot** [comment]
Looks great Michal! We're almost there :slightly_smiling_face: Just a few things more:
* There's still the problem with the logo animation. When you go from a different [page](https://frontity-org-iwb96voyi.now.sh/) to the [homepage](https://frontity-org-iwb96voyi.now.sh/homepage),  the logo in the iframe is pixeled.
Screenshot from 2020-04-16 08-40-31
* I've seen that you added some background to the header, but I think it should be transparent, as it may vary on each page. Maybe we have to position the header absolutely and adding some margins, don't know.
* I am not sure about the problem with the background triangles. As far as I know if you change the background to transparent in [this line](https://github.com/frontity/frontity.org/blob/dev/packages/frontity-org-theme/src/components/background-with-triangles.tsx#L56) and add the correct `z-index` it should work. Are there any other problems?

**Comment by michalczaplinski** [comment]
> Looks great Michal! We're almost there 🙂 Just a few things more:
> 
> * There's still the problem with the logo animation. When you go from a different [page](https://frontity-org-iwb96voyi.now.sh/) to the [homepage](https://frontity-org-iwb96voyi.now.sh/homepage),  the logo in the iframe is pixeled.

yeah, I've seen it now and I dont underststand it 😅 I will have a look, but if I'm stuck I ll just move on cause it's not a big issue.

> * I've seen that you added some background to the header, but I think it should be transparent, as it may vary on each page. Maybe we have to position the header absolutely and adding some margins, don't know.

Good point, I think you're right 👍 

> * I am not sure about the problem with the background triangles. As far as I know if you change the background to transparent in [this line]
(https://github.com/frontity/frontity.org/blob/dev/packages/frontity-org-theme/src/components/background-with-triangles.tsx#L56) and add the correct `z-index` it should work. 

hmm, I ll check this, thanks!

**Comment by michalczaplinski** [comment]
@SantosGuillamot  Oh, by the way, the thing with the triangles background is not going to work for the following (and really annoying) reason:

The background of the whole page is `f6f6f9` (let's just call it grey, it's gonna be important later)

Now, we want to add the color to the hero section. Let's say we add the color like: `background-color: #f2f3fc` (without the alpha). Then, if we want to add the triangles we have to added them "on top" of this element using the `z-index` because the backgound of the Hero is solid and otherwise the triangles are hidden behind it. But, if we give the triangles a `z-index` higher than that of the Hero section the triangles are going to be _on top_ of all the content in the Hero.

Okay, so how about we make the `background-color` semi-transparent by adding opacity? Something like: `background-color: ${({colors}) => addAlpha(colors.frontity, 0.08)}`. Well, this won't work because remember that the whole page has a grey background, so the color of the hero will mix with that color and end up incorrect.

Let's just use an SVG image as a background, it should load instantly and get rid of all our problems.

**Comment by SantosGuillamot** [comment]
Great, thanks for the explanation Michal! Some things to consider:
* Regarding the triangles as you prefer, just keep in mind that they aren't only used in the homepage but also in the rest of the pages, with a slightly different format. Anyway, if it's causing a lot of troubles we can released a first version without the triangles.
* I've seen that you add some padding to the `hero`. I'm not sure if it's better to add this to all the pages, because it'd affect every page. Maybe adding it at the `<Page />` component?
* I think you added a margin to the ordered lists that is affecting the `terminal` and is looking kind of weird. Should we only include that margin in the sections that apply or remove it from the `terminal`?
* Apart from that, I've seen that the unordered lists marker is not vertically aligned anymore. I think we should fix that as well.
Screenshot from 2020-04-17 08-34-01

**Comment by SantosGuillamot** [comment]
I've updated the content of the homepage so you can tests the styles with the final version. If you look at the `Frontity flow` section, it seems that there's a problem when the code is longer than expected (the `Connect` step). It the terminal should be the one scrolling. And maybe we could increase the height a bit to show the whole code at first sight anyway.

Feel free to go for the solution you feel it's better, we can change that afterwards.

**Comment by michalczaplinski** [comment]
> Apart from that, I've seen that the unordered lists marker is not vertically aligned anymore. I think we should fix that as well.

Hmm, it seems to be for me - what system are you on?
Screenshot 2020-04-17 at 10 11 29

Good points about everything else that you mentioned! 🙂

**Comment by michalczaplinski** [comment]
> The triangles

yeah, I ll tackle it last, maybe we can just release without it if you don't want to make the background an SVG. I don't see a different and easy solution at the moment

> Adding paddig to the `<Page />` 

Makes sense, will do.

> terminal margins and overflow

I've added a bit of CSS to fix the overflowing 
I think the code examples shouldn't need to scroll because it's a bad user experience so I've just made the code shorter in wordpress and adjusted some paddings & margins in the terminal.


Also:

1. I've added `$` instead of line numbers in the terminal because like Jude mentioned already, they make much more sense and I also think they look better. 

2. Fixed the padding and margins for `ol` `ul` and `li`

2. Fixed the CSS paddings and margins down to the "Why React? Why Wordpress?" section

**Comment by SantosGuillamot** [comment]
>if you don't want to make the background an SVG.

I didn't mean that sorry, if you think the SVG is a better and easy option let's go for it.

If you feel it's going to take too much time I think we can still use the component we have (making the `background` transparent) and maybe not include it in the homepage, but I think it's good with the current implementation for the rest of the pages. We could do something like `!data.isHome && <Triangles />`. Or we could even keep it overlaping the terminal, although I feel is better without it.

With the triangles:
Screenshot from 2020-04-20 09-39-45

Without the triangles:
Screenshot from 2020-04-20 09-41-01

>what system are you on?

I am using Google Chrome 80.0.3987.132 in Ubuntu.

>terminal margins and overflow

The scrolling bars look pretty weird in Ubuntu, I think we should get rid of them. Maybe using `overflow: hidden`?

Screenshot from 2020-04-20 09-53-14
Screenshot from 2020-04-20 09-53-30

**Pull request merged**
