### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by luisherranz**
A simple update of the Frontity dependencies.

### CODE REVIEW

**Comment by luisherranz** [comment]
@SantosGuillamot do you usually add changesets when updating dependencies?

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit f412623a5d63747e5d79010cb6c9e9b5ebfe1aca

https://frontity-org-20581yeig-frontity.vercel.app

**Review by SantosGuillamot — APPROVED** [review]
LGTM :slightly_smiling_face:

**Comment by SantosGuillamot** [comment]
> @SantosGuillamot do you usually add changesets when updating dependencies?

I think it isn't necessary in this case if we are only updating dependencies.

**Comment by SantosGuillamot** [comment]
Well, honestly I don't know if after merging dev into master, if there aren't any changeset, it's going to work as expected. We can try.

**Comment by luisherranz** [comment]
Ok, let's try.

**Comment by luisherranz** [comment]
Ok, it didn't work 😄

Screenshot 2021-04-16 at 11 48 07

The GH action didn't create the PR.

**Comment by SantosGuillamot** [comment]
It didn't create the Pull Request but I think it did the deploy to frontity.org. At least I received an email pointing to this message -> https://github.com/frontity/frontity.org/commit/5de165c5e0758737db6caa2e7d26dac277c91d78#commitcomment-49594372

**Comment by SantosGuillamot** [comment]
I've checked Vercel and it did a deploy 2 hours ago in the production domain, so I guess it worked 🙂 .

**Comment by luisherranz** [comment]
Oh, nice then 🙂

**Pull request merged**
