### PR TITLE
Change import of processors

### PR DESCRIPTION
**Pull request by kasperaamodt**
Hi,

This is a fix for issue #190

### CODE REVIEW

**Comment by michalczaplinski** [comment]
I'm sorry I meant to merge #192 but I've merged this one before reviewing it because I'm dumb 🤓

**Comment by michalczaplinski** [comment]
@kasperaamodt Would you mind re-opening the PR? 

I've reviewed the changes: I'm fine with the re-organization of processors because named exports are generally better. I only wonder why [`fd935ef` (#189)](https://github.com/frontity/frontity.org/pull/189/commits/fd935efb3899c2254fb73a982bc52adf0e6d9239) was necessary? `state.source.api` should always be ending in slash - do you have a reproduction when this is not the case?

**Comment by michalczaplinski** [comment]
@kasperaamodt Would you also mind adding a changeset in the new PR?

https://github.com/atlassian/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo

**Comment by kasperaamodt** [comment]
Hi @michalczaplinski,

[fd935ef (#189)](https://github.com/frontity/frontity.org/pull/189/commits/fd935efb3899c2254fb73a982bc52adf0e6d9239) I necessary because the state.source.api returns a URL with a '/' at the end, so when you also add it straight after, the request URL is actually .../wp-json//contact-form-7/..., which returns a 404 error, because it should only be one '/'.

I can read up on changeset and how to do it. :)

**Comment by kasperaamodt** [comment]
Here is the working cf7 package that a lot of people are using, that I made.

https://github.com/aamodtgroup/frontity-contact-form-7/blob/17d947df10e1dd44a6f7453a1128a6ba75962239/src/index.js#L90

**Comment by michalczaplinski** [comment]
> Is necessary because the state.source.api returns a URL with a '/' at the end,

Oh, you're absolutely right 🤦 For some reason I have read that change the other way round thinking that you have **added** that extra slash. 

I have to apologize for this comedically bad review of your PRs - you'd have to take my word that we really do a better job at this normally and hope it doesn't discourage you from contributing in the future 🙂 

Will review your PR now!

**Pull request merged**
