### PR TITLE
Add no-cache header

### PR DESCRIPTION
**Pull request by SantosGuillamot**
We're moving frontity.org to Pantheon using the Theme Bridge, and we'll use their own cache system. So having `stale-while-revalidate` in Now will cause troubles.

### CODE REVIEW

**Comment by michalczaplinski** [comment]
The CI failing seems  to be caused by the github action to add the PR comment failing: https://github.com/frontity/frontity.org/pull/107/checks?check_run_id=676275381#step:7:8

I’ve opened the issue https://github.com/iam4x/now-deploy-preview-comment/issues/3 but in the meantime I guess we can disable it or switch to https://github.com/marketplace/actions/zeit-now-deployment

**Comment by luisherranz** [comment]
Could you please check if this is related to the changes in this PR or it happens on any new PR?

**Comment by SantosGuillamot** [comment]
I created [this PR](https://github.com/frontity/frontity.org/pull/108/) and, although it didn't pass the tests at the beginning, after adding the `scope: frontity` the problem was solved. So I guess the problem is different because I added it here and it's still not working.

I've just seen that in the checks we're getting this message:
```
Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .vercelignore):
- {"src":"build/server.js","use":"@now/node"}
```

I'm going to investigate a bit there.

**Comment by michalczaplinski** [comment]
You're right @SantosGuillamot .

The now deployment fails but it still returns OK status back to github so that causes the next step (add github PR comment) to fail. 

Could you investigate it?

**Comment by SantosGuillamot** [comment]
Yes, I'll take a look.

**Comment by michalczaplinski** [comment]
thank you @SantosGuillamot  🙂

**Comment by luisherranz** [comment]
The error says `build/server.js` doesn't exist.

The `@frontity/now` builder does the `npx frontity build` on the Now servers. 

We're not using that anymore, so we need to do the build ourselves.

You can add it to the workflow, previous to the deploy.

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit dd60444c2c91c13e5be60ac80d60df69dc799517

https://frontity-org-avyqmxjbl.now.sh

**Comment by SantosGuillamot** [comment]
It seems that solved the problem, thanks @luisherranz  :slightly_smiling_face:

**Comment by luisherranz** [comment]
Nice, it's really slow now 💪 😆

**Pull request merged**
