### PR TITLE
Newsletter logic

### PR DESCRIPTION
**Pull request by SantosGuillamot**
In order to test if the old logic was reusable I kind of migrated to the new web, in case it's useful for the final implementation. It works except some things I'm aware that should be improved:

- [x] Clean the code, right now it's a bit mess.
- [x] Finish the styles.

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 4b39321e1f01dff59767f73570791e20cc190862

https://frontity-org-ck7bxdh6r.now.sh

**Comment by luisherranz** [comment]
Nice work @SantosGuillamot!

I have refactored the code to help you structure things a little better. Also, typescript was right but it was not being applied. Take a look at the commits and commit messages and if you have any question let me know 👍

**Comment by michalczaplinski** [comment]
@SantosGuillamot Leaving this in blocked for the moment as it's waiting on https://github.com/frontity/frontity/pull/371 in order to send the correct events

**Comment by SantosGuillamot** [comment]
Looks great Michal! Some minor details that I'd implement if they aren't too difficult:
* The current submit buttons have a weird border. I will delete it.
* Once the input of the email is active, I'd add a border with `frontity` color to the whole box.
* In the input of the afternewsletter, I'd use the same colors as in the one for the email.
* I'd add some margin at the top for the mobile version.
* In the current newsletter, the checkboxes and radio inputs are styled with Frontity colors, if it's easy I'd do something similar:

Checkbox
Screenshot from 2020-04-15 08-40-04

Radio input
Screenshot from 2020-04-15 08-40-31

**Pull request merged**
