### PR TITLE
Add the intersection-observer polyfill

### LINKED ISSUE #100: frontity.org not working in Safari 11.1
**Observed behavior**
When you visit the frontity.org website in Safari 11.1 the screen goes blank.

frontityorg-safari

frontityorg-safari02

### PR DESCRIPTION
**Pull request by michalczaplinski**
This fixes #100 .

The polyfill is needed because some browsers (most notably Safari < 11) do not ship with `IntersectionObserver` API

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 8128bae8c46a1d9fb87396fef83d783966cc0355

https://frontity-org-38r2j9kk9.now.sh

**Comment by michalczaplinski** [comment]
The deploy URL is returning an internal server error.

The Vercel logs for the serverless function https://vercel.com/frontity/frontity-org/38r2j9kk9 are showing the following: 

```
2020-04-30T23:42:52.648Z	7e25cce0-0339-446c-8195-736dd4d430f6	ERROR	Jn [ServerError]: post type from endpoints "template-parts" with slug "header" not found
    at Object.func (/var/task/index.js:222:32688)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/index.js:222:36954 {
  name: 'ServerError',
  status: 404,
  statusText: 'post type from endpoints "template-parts" with slug "header" not found'
}
2020-04-30T23:42:53.072Z	7e25cce0-0339-446c-8195-736dd4d430f6	ERROR	undefined
2020-04-30T23:42:53.072Z	7e25cce0-0339-446c-8195-736dd4d430f6	ERROR	  TypeError: Cannot read property 'content' of undefined
      at /var/task/index.js:212:156118
      at d (/var/task/index.js:1:42831)
      at t (/var/task/index.js:1:43394)
      at /var/task/index.js:1:50179
      at a (/var/task/index.js:188:11040)
      at ke (/var/task/index.js:188:12058)
      at e.t.render (/var/task/index.js:188:14574)
      at e.t.read (/var/task/index.js:188:14150)
      at renderToString (/var/task/index.js:188:19751)
      at /var/task/index.js:222:121395
2020-04-30T23:42:53.072Z	7e25cce0-0339-446c-8195-736dd4d430f6	ERROR	undefined
```

I fail to understand how this is related to the changes in any way 🤔

**Comment by luisherranz** [comment]
Doesn't seem related: `post type from endpoints "template-parts" with slug "header" not found`

**Comment by luisherranz** [comment]
The problem seems related to this fix: https://github.com/frontity/frontity.org/pull/102

**Comment by michalczaplinski** [comment]
@SantosGuillamot Let's merge for the moment, this [like Luis mentioned](https://github.com/frontity/frontity.org/issues/100#issuecomment-625195055) and we can work on improving the intersection observer hook in the meantime 🙂

**Comment by SantosGuillamot** [comment]
I have one quick question before approving it: is there a way to test if this solves the problem?

I've done some tests on Internet Explorer, which doesn't support `IntersectionObserver`, and I'm not able to reproduce the problem. Frontity is loading correctly. Shouldn't it be the same as with Safari 11?

**Comment by luisherranz** [comment]
IE doesn't load the JS of Frontity, is SSR-only, so it won't fail there.

Maybe we need an account on BrowserStack or CrossBrowserTesting.

**Comment by michalczaplinski** [comment]
I would second getting an account on BrowserStack. I at don't have the GBs to run VMs on my laptop at the moment and we are running into some browser compatibility issues every now and then 🙁 

In the meantime, @rmartinezduque could you check if this works on Safari 11 :https://frontity-org-bfs2mnvnh.now.sh/ ? Thanks 🙂

**Comment by rmartinezduque** [comment]
@michalczaplinski, yes, it is working. 🙂 Now I've noticed that the font of the headings does not apply the bold style. Here are some screenshots in comparison with the Chrome browser.

I'm not sure if this is a different issue so let me know if you prefer me to open a new one fo this. Thanks!

comparison-01
comparison-02

**Comment by michalczaplinski** [comment]
Thanks @rmartinezduque!  

Yep, this is a different problem. I've opened a [new issue](https://github.com/frontity/frontity.org/issues/106) feel free to add if I've missed something.

**Pull request merged**
