### PR TITLE
Add button processor

### PR DESCRIPTION
**Pull request by michalczaplinski**
Closes: #1

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 5680c43bd92d07598160d41f7929570b9015cea4

https://frontity-org-mgfp3qa5j.now.sh

**Comment by michalczaplinski** [comment]
> Looks great Michal! I just have two points:
> 
> * Is the `default-button` class needed?
It's possible to NOT use it but it makes the logic for matching elements in processors much easier. Otherwise, I would have to check if we DO NOT have every other possible class basically. Is it a problem?

> * Right now, if we use the `big-button` class in a button with a custom icon (like the demo), it adds the frontity logo as well.
oh, will fix that!

**Comment by luisherranz** [comment]
> but then we have to make sure that this particular processor runs last!

You can add different priorities to each processor.

**Comment by michalczaplinski** [comment]
@SantosGuillamot @luisherranz I kind of forgot about the `priority`, but it doesn't help much in this case. Or at least it doesn't make the implementation simpler (I've just tried it).

Ive watched the morning standup and I get your concern about not having a "default" style for buttons that don't have the `button-default` class 🙂. I thought that this was not a big deal and makes the code for processors simpler in my opinion, but let me know, Mario if this is a must or if we can live with having to add a `button-default` class. 

I can change the implementation accordingly.

**Comment by SantosGuillamot** [comment]
I've been taking a deeper look at the solution and I have one question. I'm pretty sure there's a reason for it but wouldn't be better to use just one processor for all the different links/buttons? I've seen that you are using one processor for `buttonDefault`, `commonLink`, `buttonBig`, `buttonIcon` and `buttonLink`, but there is some code duplicated between them. Apart from that, I think there are some things "hardcoded" like the height, width or color of the `button-icon`, which would make us lose flexibility for future custom buttons.

I've done a quick test of how a unified processor could be and it seems to be working. I've created a branch to test it (I'm sure it could be cleaner). You can check it here -> https://github.com/frontity/frontity.org/blob/test-button-processor/packages/frontity-org-theme/src/processors/links-buttons.tsx.

This way, buttons would work by default and we'd just need to use three classes:
* `button-big`: If we want to use the bigger button.
* `no-logo`: If we don't want to use the Frontity logo or we want to use a custom one like in the demo.
* `button-text`: If we want the button to behave like the `Text Button` defined in [the issue](https://github.com/frontity/frontity.org/issues/1).

I would like to know your insights to understand better why dividing it in different processors is a better option.

**Comment by luisherranz** [comment]
Wouldn't it be easier to use a React component for this?

- The processor can translate classes to more specific props like `size="big"`, `color="#XXX"`, `radius={8}` and so on, to keep the React component as decoupled to the HTML as possible.
- Make sure to add `className` as a prop in that React component so the CSS processors can modify it.
- Use a low priority like `priority: 50` to make sure all the CSS processors are applied before.

By the way, I thought we had general CSS processors for things like background, color, radius and so on. And that is true, why do we have to duplicate that code here?

**Comment by SantosGuillamot** [comment]
>By the way, I thought we had general CSS processors for things like background, color, radius and so on. And that is true, why do we have to duplicate that code here?

You're totally right, we just had to add a priority, I've updated it removing them.

>Wouldn't it be easier to use a React component for this?

As you think it's better, we'd have to be careful of making it run the last one as you said.

**Comment by michalczaplinski** [comment]
@SantosGuillamot 

Nice job on the text-processor 🙂 

There are some issues still: 
1. The icon button still contains the fronitty logo (need to add a conditional to remove the default logo)
2. The text button has wrong color on hover 

Will fix those right now.

Adding it makes the logic a bit more complicated, so this is why I've split the processors into separate files before. I've tried to put in the one file at first :) 

However, since we want to have a default style in the absence of all classes, it makes most sense to put it all in one file.

**Comment by michalczaplinski** [comment]
Updated based on the changes from @SantosGuillamot in https://github.com/frontity/frontity.org/blob/test-button-processor/

**Comment by michalczaplinski** [comment]
@iamuchejude Could you give me a review? 🙂

**Pull request merged**
