### PR TITLE
Adapt links processor to new Gutenberg version (8.4)

### PR DESCRIPTION
**Pull request by SantosGuillamot**
The new version of the Gutenberg plugin changes the html format of the links, so we need to adapt our processor to match this html. It's adding a parent `<div>`, which is the one receiving the classes added from the WordPress dashboard. In order to adapt it, I added a check for the `node.parent` instead of just `node`.

## Previous HTML

```
<a class="wp-block-button wp-block-button__link button-text" href="https://docs.frontity.org/getting-started/" >Learn more</a>
```

## New HTML

```
<div class="wp-block-button button-text">
  <a class="wp-block-button__link" href="https://docs.frontity.org/getting-started/" >Learn more</a>
</div>
```

As we don't have the latest version in our current web (it would break some things), we can test it pointing the project to https://snippets-frontity-org.pantheonsite.io/, where we have installed Gutenberg 8.4 version.

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 3660a8fe3eb3d968ca4ccda5b12efcd89593b69a

https://frontity-org-8fs3co5og.vercel.app

**Comment by SantosGuillamot** [comment]
I had to create another environment to update the plugin without breaking the web. The preview generated is pointing to frontity.org, which isn't updated and the HTML is different. We should work on a shared repo with Frontity and WordPress, or work with ENV variables, so this doesn't happen, but I haven't had time to do so.

**Comment by luisherranz** [comment]
Shouldn't that be solved once the Pantheon integration is finished and Frontity is deployed to Pantheon as well?

**Comment by michalczaplinski** [comment]
Let us know what is your plan though in terms of changing how we're doing deployment for the website :) AFAIK we going to move from Vercel to Pantheon altogether, right?

What about the branch previews? Can we do it with pantheon as well? 

Can we deploy automatically on push to master with pantheon like we do now through the `deploy-production.yml` github workflow?

**Comment by SantosGuillamot** [comment]
Sorry I didn't answer this before!

>AFAIK we going to move from Vercel to Pantheon altogether, right?

Right, the plan is to investigate the best way to have everything in Pantheon.

>What about the branch previews? Can we do it with pantheon as well?

I think so. Pantheon has a feature named [Multidev](https://pantheon.io/docs/multidev), which create different branches from the `dev` branch.

>Can we deploy automatically on push to master with pantheon like we do now through the deploy-production.yml github workflow?

Not sure of this. In Pantheon they work with three main environments: dev, test and live. As far as I know, you can only make changes to `dev` and once you want to merge it there's a workflow in Pantheon interface.

**Pull request merged**
