### PR TITLE
Headless flow

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is the headless flow component:
Screenshot 2020-04-01 at 13 51 21

Please note that
-  We're still missing some global padding for some of the elements of that whole section "How Frontity Works"
- The solution is a bit hacky and I think that it's not pixel-perfect, but I cannot justify spending more time on it, since it's not really providing a lot of value to the user.

### CODE REVIEW

**Comment by frontibotito** [comment]
Deploy preview for _website_ ready!

Built with commit 873c0b1fa2e7921e27d2b68f8376eac874744b2c

https://frontity-org-nodapj6qu.now.sh

**Comment by DAreRodz** [comment]
Hey, @michalczaplinski, I don't how important is this (@SantosGuillamot could tell us), but the `useMedia` hook you are using doesn't work in SSR so, in the mobile view, the dots are rendered in a row until the JavaScript code runs a detects the screen dimensions.

Maybe there is a way to solve that just using CSS.


dots-mobile

**Comment by michalczaplinski** [comment]
@DAreRodz good point, I've fixed that 👍

**Comment by SantosGuillamot** [comment]
I hadn't noticed that :smile: In my opinion is perfect, good to go! :slightly_smiling_face:

**Comment by michalczaplinski** [comment]
@DAreRodz Could you review this? 🙂

**Pull request merged**
